apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devopsdojo.configMapName" . }}
  namespace: {{ include "devopsdojo.namespace" . }}
  labels:
    {{- include "devopsdojo.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  DB_HOST: {{ include "devopsdojo.database.host" . | quote }}
  DB_PORT: {{ .Values.database.external.port | default "5432" | quote }}
  DB_NAME: {{ .Values.database.external.name | default "postgres" | quote }}
  FLASK_DEBUG: {{ .Values.backend.env.flaskDebug | default "0" | quote }}
  BACKEND_URL: {{ include "devopsdojo.backend.url" . | quote }}
