# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: devopsdojo-dev-secrets
#   namespace: devopsdojo-dev
# spec:
#   refreshInterval: 1h

#   secretStoreRef:
#     name: azure-keyvault
#     kind: ClusterSecretStore

#   # data:
#   #   - secretKey: DB_PASSWORD
#   #     remoteRef:
#   #       key: postgres-password
#   #   - secretKey: DB_USERNAME
#   #     remoteRef:
#   #       key: postgres-username
#   #   - secretKey: DATABASE_URL
#   #     remoteRef:
#   #       key: database-url

#   target:
#     name: devopsdojo-dev-secrets
#     creationPolicy: Owner
#     template:
#       type: Opaque
#       data:
#         # From values.yaml (non-sensitive)
#         # SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
#         - secretKey: DB_PASSWORD
#           remoteRef:
#             key: postgres-password
#         - secretKey: DB_USERNAME
#           remoteRef:
#             key: postgres-username
#         - secretKey: DATABASE_URL
#           remoteRef:
#             key: database-url

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "devopsdojo.secretName" . }}
  namespace: {{ include "devopsdojo.namespace" . }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore

  target:
    name: {{ include "devopsdojo.secretName" . }}

  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: postgres-password
    - secretKey: DB_USERNAME
      remoteRef:
        key: postgres-username
    - secretKey: DATABASE_URL
      remoteRef:
        key: database-url