{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devopsdojo.frontend.serviceName" . }}
  namespace: {{ include "devopsdojo.namespace" . }}
  labels:
    {{- include "devopsdojo.frontend.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "devopsdojo.frontend.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "devopsdojo.frontend.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          env:
            - name: BACKEND_URL
              value: {{ include "devopsdojo.backend.url" . | quote }}
            - name: PORT
              value: {{ .Values.frontend.service.port | quote }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.healthCheck.path }}
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.healthCheck.periodSeconds }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}
