{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devopsdojo.frontend.serviceName" . }}
  namespace: {{ include "devopsdojo.namespace" . }}
  labels:
    {{- include "devopsdojo.frontend.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "devopsdojo.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
