{{- if .Values.secrets.createLocalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devopsdojo.secretName" . }}
  namespace: {{ include "devopsdojo.namespace" . }}
  labels:
    {{- include "devopsdojo.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.secrets.dbUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.secrets.dbUsername .Values.secrets.dbPassword (include "devopsdojo.database.host" .) (.Values.database.external.port | default "5432") (.Values.database.external.name | default "postgres") | b64enc | quote }}
{{- end }}
