frontend:
  replicaCount: 2

api:
  replicaCount: 2

admin:
  replicaCount: 2

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  frontendHost: shop-lddemo.nya.pub
  apiHost: api-shop-lddemo.nya.pub
  tls:
    enabled: true
    frontendSecretName: shop-demo-local-tls
    apiSecretName: api-shop-demo-local-tls

# 74.177.187.254 shop.demo.local api.shop.demo.local
