replicaCount: 2

image:
  repository: helmdemold.azurecr.io/todo-api
  pullPolicy: IfNotPresent
  tag: "v1"

service:
  type: ClusterIP
  port: 3000

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

vpa:
  enabled: true
  updateMode: "Auto"

networkPolicy:
  enabled: true

pdb:
  enabled: true
  minAvailable: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env: "dev"