apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  app.conf: |
    server {
      listen 80;
      location / {
        return 200 "Hello from ConfigMap\n";
      }
    }
  APP_MODE: "production"
  LOG_LEVEL: "info"
