apiVersion: v1
kind: Pod
metadata:
  name: demo-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - uksouth-2
      # preferredDuringSchedulingIgnoredDuringExecution:
      # - weight: 100
      #   preference:
      #     matchExpressions:
      #     - key: topology.kubernetes.io/zone
      #       operator: In
      #       values:
      #       - uksouth-1
  containers:
  - name: nginx
    image: nginx:1.25