apiVersion: v1
kind: Pod
metadata:
  name: demo-toleration
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "demo"
    effect: "NoSchedule"
  nodeSelector:
    topology.kubernetes.io/zone: uksouth-2
  containers:
  - name: nginx
    image: nginx:1.25
