# Test - kubectl auth can-i get pods --namespace=demo --as=:demo:demo-sa
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: demo
#   name: developer
# rules:
# - apiGroups: [""]
#   resources: ["pods", "pods/log"]
#   verbs: ["get", "list", "watch"]
# - apiGroups: ["apps"]
#   resources: ["deployments"]
#   verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demo
  name: read-only
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: student-binding
  namespace: demo
subjects:
- kind: User
  name: student-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-only
  apiGroup: rbac.authorization.k8s.io
