apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop-demo.fullname" . }}-admin
  labels:
    {{- include "shop-demo.labels" . | nindent 4 }}
    app: admin
spec:
  type: {{ .Values.admin.service.type }}
  selector:
    app: admin
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: {{ .Values.admin.service.port }}
    targetPort: {{ .Values.admin.containerPort }}
    protocol: TCP
