apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shop-demo.fullname" . }}-frontend
  labels:
    {{- include "shop-demo.labels" . | nindent 4 }}
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
