apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop-demo.fullname" . }}-frontend
  labels:
    {{- include "shop-demo.labels" . | nindent 4 }}
    app: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.containerPort }}
    protocol: TCP
