name: Build and Push Docker Images for Capstone project

on:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'frontend/**'
  #     - 'backend/**'
  workflow_dispatch:  # Enable manual triggering

env:
  ECR_REPOSITORY_FRONTEND: devopsdozo/frontend
  ECR_REPOSITORY_BACKEND: devopsdozo/backend
  ECR_REGISTRY: "azurelddemo.azurecr.io"
  IMAGE_TAG: ${{ github.sha }}
  WORKING_DIR: "kubernetes/capstone"

jobs:
  # changes:
  #   name: Detect Changes
  #   runs-on: ubuntu-latest
  #   outputs:
  #     frontend: ${{ steps.filter.outputs.frontend }}
  #     backend: ${{ steps.filter.outputs.backend }}
    
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
          
  #     - name: Check for file changes
  #       id: filter
  #       uses: dorny/paths-filter@v2
  #       with:
  #         filters: |
  #           frontend:
  #             - 'frontend/**'
  #           backend:
  #             - 'backend/**'

  # build-and-push-frontend:
  #   name: Build and Push Frontend Image
  #   environment: dev
  #   # needs: changes
  #   # if: ${{ needs.changes.outputs.frontend == 'true' || github.event_name == 'workflow_dispatch' }}
  #   runs-on: self-hosted
    
  #   permissions:
  #     id-token: write
  #     contents: write
      
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
        
  #     - name: Azure login
  #       uses: azure/login@v2
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
  #     - name: Login to ACR
  #       run: |
  #         az acr login --name ${{ env.ECR_REGISTRY }}

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Buildx
  #       uses: docker/setup-buildx-action@v3
        
  #     - name: Build and push Docker image Frontend
  #       working-directory: ${{ env.WORKING_DIR }}/frontend/
  #       run: |
  #         docker buildx build --platform linux/arm64 -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }} . --push

  #     - name: Update Kubernetes deployment manifest Frontend
  #       working-directory: ${{ env.WORKING_DIR }}/k8s
  #       run: |

  #         # Update the image in the deployment file
  #         sed -i "s|image:.*frontend.*|image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_FRONTEND }}:${{ env.IMAGE_TAG }}|g" \
  #           frontend.yaml

  #         echo "Updated Frontend yaml with new image tag -> ${{ env.IMAGE_TAG }}"
  #         echo "Image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_FRONTEND }}:${{ env.IMAGE_TAG }}"

  #         sed -i '/^frontend:/,/^backend:/ { /^ *tag:/ s|^\([[:space:]]*tag:[[:space:]]*\).*|\1${{ env.IMAGE_TAG }}| }' ../helm/devopsdojo/values.yaml
  #         echo "Updated values.yaml frontend with new image tag -> ${{ env.IMAGE_TAG }}"

  #     - name: Commit and push updated manifests Frontend
  #       working-directory: ${{ env.WORKING_DIR }}/k8s
  #       run: |
  #         git config --global user.name "github-actions[bot]"
  #         git config --global user.email "github-actions[bot]@users.noreply.github.com"
  #         git add frontend.yaml ../helm/devopsdojo/values.yaml
  #         git diff --staged --quiet || git commit -m "Update Frontend image to ${{ env.IMAGE_TAG }} tag"
  #         git pull --rebase origin ${{ env.environment_branch }}
  #         git push --force origin ${{ env.environment_branch }}

  build-and-push-backend:
    name: Build and Push Backend Image
    environment: dev
    # needs: changes
    # if: ${{ needs.changes.outputs.backend == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: self-hosted
    
    permissions:
      id-token: write
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Login to ACR
        run: |
          az acr login --name ${{ env.ECR_REGISTRY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker image Backend
        working-directory: ${{ env.WORKING_DIR }}/backend/
        run: |
          docker buildx build --platform linux/arm64 -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_BACKEND }}:${{ github.sha }} . --push

      - name: Update Kubernetes deployment manifest Backend
        working-directory: ${{ env.WORKING_DIR }}/k8s
        run: |

          # Update the image in the deployment file
          sed -i "s|image:.*backend.*|image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_BACKEND }}:${{ env.IMAGE_TAG }}|g" \
            backend.yaml

          echo "Updated Backend yaml with new image tag -> ${{ env.IMAGE_TAG }}"
          echo "Image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_BACKEND }}:${{ env.IMAGE_TAG }}"

          sed -i '/^backend:/,/^database:/ { /^ *tag:/ s|^\([[:space:]]*tag:[[:space:]]*\).*|\1${{ env.IMAGE_TAG }}| }' ../helm/devopsdojo/values.yaml
          echo "Updated values.yaml backend with new image tag -> ${{ env.IMAGE_TAG }}"

      - name: Commit and push updated manifests Backend
        working-directory: ${{ env.WORKING_DIR }}/k8s
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add backend.yaml ../helm/devopsdojo/values.yaml
          git diff --staged --quiet || git commit -m "Update Backend image to ${{ env.IMAGE_TAG }} tag"
          git pull --rebase origin ${{ env.environment_branch }}
          git push --force origin ${{ env.environment_branch }}
