name: Helm Deploy
run-name: "Helm Deploy: ${{ github.event.head_commit.message || github.workflow }}"

on:
  workflow_run:
    workflows: ["CICD Merge Workflow"]
    types:
      - completed
  workflow_dispatch:

# on:
#   workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  myAKSCluster: "aks-prod-uksouth-01"
  myResourceGroup: "rg-aks-prod-uksouth-01-dev"
  WORKING_DIR: "kubernetes/argocd"
  GITHUB_TOKEN: ${{ github.token }}


jobs:
  helm-deploy:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: dev
    name: Deploy Helm Chart
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
      
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Install kubelogin
        run: |
          KUBELOGIN_VERSION=v0.0.32
          curl -LO https://github.com/Azure/kubelogin/releases/download/${KUBELOGIN_VERSION}/kubelogin-linux-amd64.zip
          unzip kubelogin-linux-amd64.zip
          mkdir -p $HOME/bin
          mv bin/linux_amd64/kubelogin $HOME/bin/
          chmod +x $HOME/bin/kubelogin
          echo "$HOME/bin" >> $GITHUB_PATH
          $HOME/bin/kubelogin --version

      - name: Set up kubeconfig
        run: |
          az aks get-credentials --resource-group ${{ env.myResourceGroup }} --name ${{ env.myAKSCluster }} --overwrite-existing

      - name: Convert kubeconfig
        run: |
          kubelogin convert-kubeconfig -l azurecli

      - name: Deploy Ingress Chart
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update

          # Install (creates LoadBalancer)
          helm upgrade --install nginx-ingress ingress-nginx/ingress-nginx \
            --namespace ingress-nginx --create-namespace \
            --set controller.service.type=LoadBalancer \
            --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"="/healthz"

      - name: Deploy Cert-Manager Chart
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update

          # Install cert-manager (creates LoadBalancer)
          helm upgrade --install cert-manager jetstack/cert-manager \
            --namespace cert-manager --create-namespace \
            --set installCRDs=true

      - name: Apply ClusterIssuer yaml
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          kubectl apply -f cluster-issuer.yaml

      - name: Deploy ArgoCD Chart
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update
          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd \
            --create-namespace \
            --set crds.install=true

      - name: Apply ClusterIssuer yaml
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo "Current path: $(pwd)"
          echo "Listing files in working directory:"
          ls -la ${{ env.WORKING_DIR }}
          kubectl apply -f argo-ingress.yaml